"""added new modela dn updated other two

Revision ID: 1f11c6cc2916
Revises: 5497b04a6a8c
Create Date: 2025-08-29 19:44:24.674196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f11c6cc2916'
down_revision: Union[str, Sequence[str], None] = '5497b04a6a8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('linkedin', sa.String(), nullable=True),
    sa.Column('twitter', sa.String(), nullable=True),
    sa.Column('company_context', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_index(op.f('ix_companies_company_id'), 'companies', ['company_id'], unique=False)
    op.add_column('job_posts', sa.Column('company_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'job_posts', 'companies', ['company_id'], ['company_id'])
    op.add_column('user_profile', sa.Column('past_work_links', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'past_work_links')
    op.drop_constraint(None, 'job_posts', type_='foreignkey')
    op.drop_column('job_posts', 'company_id')
    op.drop_index(op.f('ix_companies_company_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
