"""updated the resume absolute link

Revision ID: 5497b04a6a8c
Revises: bce8c52c1fa3
Create Date: 2025-08-29 13:25:05.282568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5497b04a6a8c'
down_revision: Union[str, Sequence[str], None] = 'bce8c52c1fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
