"""added new columns in user profile table

Revision ID: bce8c52c1fa3
Revises: b6b0f6d3c9a1
Create Date: 2025-08-29 12:46:35.590692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bce8c52c1fa3'
down_revision: Union[str, Sequence[str], None] = 'b6b0f6d3c9a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
